name: Terraform Destroy

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan-destroy:
    name: Terraform Plan Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./GithubActions-Practice

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./GithubActions-Practice

      - name: Terraform Plan Destroy (shows resources to be destroyed)
        run: terraform plan -destroy
        working-directory: ./GithubActions-Practice

  terraform-destroy:
    name: Terraform Destroy Apply
    needs: terraform-plan-destroy
    runs-on: ubuntu-latest
    environment: production  # Must be protected with required reviewers for approval

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./GithubActions-Practice

      - name: Terraform Destroy (after manual approval)
        run: terraform destroy -auto-approve
        working-directory: ./GithubActions-Practice
