name: Terraform Destroy (dev)

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan:
    name: Terraform Destroy Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./GithubActions-Practice

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./GithubActions-Practice

      - name: Terraform Destroy Plan
        run: terraform plan -destroy -input=false -out=destroy.out
        working-directory: ./GithubActions-Practice

  terraform-destroy:
    name: Terraform Destroy (Needs Approval)
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: dev   # 👈 Hardcoded to dev environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./GithubActions-Practice

      - name: Terraform Destroy
        run: terraform apply -auto-approve destroy.out
        working-directory: ./GithubActions-Practice
